### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by jasonhuan** [lightclient/parrot#1]
error[E0658]: use of unstable library feature 'str_split_once': newly added
  --> src/main.rs:14:48
   |
14 |                 if let Some((_, json)) = input.split_once(": ") {
   |                                                ^^^^^^^^^^
   |
   = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

pinging @lightclient

**Comment by lightclient** [comment]
rip

**Comment by lightclient** [comment]
i must be building on nightly?

**Comment by jasonhuan** [comment]
thx for the help

for anyone else reading this:
`rustup default nightly`
`cargo +nightly build`

10/10 would build again

**Comment by habovh** [comment]
@jasonhuan I'd like to point out that this issues has been fixed and released on the stable channel since 1.52.0. You can check this commit for more details: https://github.com/rust-lang/rust/commit/0db8349fff644b0073f3560085c6266e9871bebd.

I think it's worth keeping people off nightly builds unless it's strictly necessary.
